language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
# only add the two lines below if you need wkhtmltopdf for your tests
#    sources:
#      - pov-wkhtmltopdf
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
#     Search your packages here:
#       https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
#      - wkhtmltopdf  # only add if needed and check the before_install section below

# set up an X server to run wkhtmltopdf.
#before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  # This line contains the encrypted transifex password
  # To encrypt transifex password, install travis ruby utils with:
  #   $ gem install travis --user-install
  # and use:
  #   $ travis encrypt TRANSIFEX_PASSWORD=your-password -r owner/project
  - secure: Jxuo2xgLN25ZibXNSzhgyOlbZPycT9yEAzXb3A5r56FwSpLgJ2yPmswNFDtuEFQQz0++6dXSYgWeA3BWgnrjLTxFptxAI8zBfEOXuy6KdyCxbZ3Xw9N3iPDzNZJAQFWGfiNDnaCchC0EK5yXPHJEg0gHMQoCk4QpO7BzBMumit9Rt93MlgK7hvdGi0PPI5liwCdRUAjn/tTEg0BQLTKcJpbuaqFgY2dHS0xFY0a/+NQWN6RcjpLk1+NWZ6wPvCg7nluPUqafxZI+qy1lKayopz2wyGjDtSUONuUxMT7F0lLja+U/JF61a5qRo+vq5MLxWBnNICWwX6PnNW1djsf0zWNtCNNfaQT75DPE2LPrF2Kqj1TJFW1IH7KVplJ9HGRqZa54ujemQhFT6UR+OLXzeHkUA56fIE/3MRkyq0HG2GpUDreyFAiWak4r7AOF1rhguEs0+0nNSSS8CjsSptFEqyglyA6JNbskIVMGkNC0JpEzKd81F9TH8OmhL+zjxY8CnycBp+oa0gAP0F96zx2idOyEdNV8hyPwVOMuAlAWXeR3hghrX69IPcdpL/tQC9xzvnoF3SSD+S8BZOTLK+FZWkETySAxUJbYdbxwz+zMink9xE4KAym6IQZTQZSDItENh4FYVH6XvZNqSQS/L1aBRVwRQVuhy2jLGbZh8V00BCw=
  # Use the following lines if you need to manually change the transifex project slug or/and the transifex organization.
  # The default project slug is owner-repo_name-version (with dash in the version string).
  # The default organization is the owner of the repo.
  # The default fill up resources (TM) is True.
  # The default team is 23907. https://www.transifex.com/organization/oca/team/23907/
  # - TRANSIFEX_PROJECT_SLUG=
  # - TRANSIFEX_ORGANIZATION=
  # - TRANSIFEX_FILL_UP_RESOURCES=
  # - TRANSIFEX_TEAM=

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
